### ISSUE TITLE
Is it possible to have more than one workflow and different shortcuts?

### ISSUE THREAD

**Issue by Simeonh2021** [sawhney17/logseq-custom-workflow-plugin#1]
e.g.  
set 1: todo-doing-done,(using "cmd+enter" to cycle)
set 2:to read-reading-read, (using "ctrl+enter" to cycle)
set 3:to summarize-to archive-archived, etc. (using "option+enter"to cycle)

**Comment by sawhney17** [comment]
The latest release offers this feature. You can configure this in settings.
