### ISSUE TITLE
hit error when set mod+enter to replace the default

### ISSUE THREAD

**Issue by fortunehan** [sawhney17/logseq-custom-workflow-plugin#2]
Please help to check if anything I set wrong.
![Xnip2022-03-20_16-19-12](https://user-images.githubusercontent.com/9983619/159154117-a31e9042-95f1-4725-835c-ec8d290a461b.jpg)
![Xnip2022-03-20_16-21-20](https://user-images.githubusercontent.com/9983619/159154170-5505607f-5ba6-4ac3-bc59-4db6b38528d8.jpg)

**Comment by sawhney17** [comment]
You have to go to logseq settings first and chnGe the shortcut for toggling workflow state from cmd enter to something else. Currently there is a clash between logseqs default command enter and the one you set.
