### ISSUE TITLE
Can't edit settings

### ISSUE THREAD

**Issue by kerim** [sawhney17/logseq-custom-workflow-plugin#3]
For some reason I can't edit the settings.  Could be a problem with the latest nightly build? 0.6.4+nightly20220322 (Mac version.) Even editing the JSON file and restarting doesn't help?

**Comment by sawhney17** [comment]
There’s a current issue with logseq, i’ve reported it on github in the main repo. The interim solution is editing it by giong to the plugins page -> find the custom workflows plugin -> and click the gear button and then “edit settings"

**Comment by kerim** [comment]
That seems to work.
