### ISSUE TITLE
replace the in built cmd enter flow does not work (anymore)

### ISSUE THREAD

**Issue by RalfKo** [sawhney17/logseq-custom-workflow-plugin#6]
Hi, you write in tips "_You can map the shortcut to mod+enter to replace the in built cmd enter flow for tasks with your own custom choice_"
but when I try that and logseq gives me:

> ":plugin.logseq-custom-workflows/Toggle-Workflow-State ctrl+enter Keyboard shortcut conflicts with existing shortcut: editor/cycle-todo"

(windows client that is.)

**Comment by sawhney17** [comment]
You have to also go to logseq settings and edit the keyboard shortcut for todo flow to something else

**Comment by RalfKo** [comment]
Thanks for he tip: After I disabled the default ctrl+enter hotkey this works. Thank you!
