### ISSUE TITLE
Plugin enabled but nothing works

### ISSUE THREAD

**Issue by DarthPleurotus** [sawhney17/logseq-custom-workflow-plugin#8]
Tried installing this plugin; I can't get custom workflows to work at all, either with the default keyboard shortcut or any others. I have no shortcut conflicts with other plugins or with Logseq's core functionality.

LogSeq 0.7.5
Custom-Workflows 1.1.0

**Comment by sawhney17** [comment]
Can’t replicate on my machine. I’m on a MacBook. What’s your platform?

**Comment by DarthPleurotus** [comment]
Macbook Pro (M1) running Monterey

**Comment by KyleMondron** [comment]
I have/had the same issue, working on Windows 11 Home and the logseq desktop application. Hopefully some additional details can help investigate this. 

First, I was able to get this working when I first installed it. I changed the shortcut to ctrl+shift+enter and it was working. I also tested it around my notes and really liked the functionality for quickly tagging my pages with workflow status indicators. 

After that, I installed your pomodoro plugin. I realized that after reopening logseq, the custom workflow ctrl+shift+enter no longer worked. I disabled the pomodoro plugin, and restarted logseq. Tried the command, and nothing happened. I changed 'ctrl' back to 'mod', and it was able to add the first step of the workflow cycle, but pressing it again did not advance the block through the other settings.

Thank you for your work on logseq!

**Comment by richd67** [comment]
Yes changing to ctrl did get it working again, I was able to cycle through the options.

**Comment by jessun** [comment]
I have the same problem, macbook air m1, monterey.
But after I set it up like "meta+shift+enter", the problem was solved.

**Comment by richd67** [comment]
Seems to have stopped working completely, changing the hotkeys no longer re-establishes function?

**Comment by sawhney17** [comment]
Should be fixed now thanks to @usoonees!
